version: 2

sources:
  - name: sales_db
    catalog: demo_catalog
    schema: sales_db

    tables:
      - name: employees

models:
  - name: stg_employees
    description: Cleaned employee data

    columns:
      - name: emp_id
        tests:
          - unique
          - not_null

      - name: emp_name
        tests:
          - not_null